import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from django.db import connection

sql = """
CREATE TABLE "outlets_pendingcommand" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "command" varchar(20) NOT NULL,
    "socket" varchar(1) NOT NULL,
    "value" integer NULL,
    "created_at" timestamp with time zone NOT NULL,
    "is_executed" boolean NOT NULL,
    "outlet_id" bigint NOT NULL REFERENCES "outlets_outlet" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX "outlets_pendingcommand_outlet_id_idx" ON "outlets_pendingcommand" ("outlet_id");
"""

try:
    with connection.cursor() as cursor:
        cursor.execute(sql)
    print("Table successfully created.")
except Exception as e:
    print(f"Error: {e}")
