# Generated by Django 5.2.9 on 2026-02-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('cutoff', 'Cut Off'), ('overload', 'Overload'), ('power_on', 'Power On'), ('power_off', 'Power Off'), ('warning', 'Warning'), ('reconnect', 'Reconnected'), ('disconnect', 'Disconnected')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('socket_label', models.CharField(blank=True, help_text='A or B', max_length=1)),
                ('current_reading', models.FloatField(blank=True, help_text='Current in mA at time of event', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs_test', to='outlets.outlet')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='outlets_eve_timesta_b5138d_idx'), models.Index(fields=['outlet', '-timestamp'], name='outlets_eve_outlet__16035d_idx')],
            },
        ),
    ]
