# Generated by Django 5.2.9 on 2026-02-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(choices=[('WEB_DASHBOARD', 'Web Dashboard'), ('ESP32_AUTO_CUT', 'ESP32 Auto Cutoff'), ('PIC_HARDWARE', 'PIC Hardware Button'), ('ESP32_SYSTEM', 'ESP32 System Logic')], max_length=50)),
                ('action_type', models.CharField(choices=[('TOGGLE_RELAY', 'Toggle Relay'), ('SET_THRESHOLD', 'Set Threshold'), ('ADD_DEVICE', 'Add Device'), ('DELETE_DEVICE', 'Delete Device'), ('OVERLOAD_TRIPPED', 'Overload Tripped'), ('ACK_RECEIVED', 'Command Acknowledged'), ('SYSTEM_BOOT', 'System Boot')], max_length=50)),
                ('target_device', models.CharField(help_text='e.g. 0xFE, Main Breaker, or All Devices', max_length=50)),
                ('details', models.TextField(help_text='Plain English explanation of the event')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestTelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('main_breaker_mA', models.IntegerField(help_text='Total system current in mA')),
                ('main_breaker_limit_mA', models.IntegerField(help_text='Active overload limit for main breaker')),
                ('device_id', models.CharField(help_text='Hex ID of the PIC device (e.g. 0xFE)', max_length=50)),
                ('device_limit_mA', models.IntegerField(help_text='Overload limit for this specific device')),
                ('socket_a_state', models.BooleanField(help_text='Is Socket A ON (True) or OFF (False)')),
                ('socket_a_mA', models.IntegerField(help_text='Current draw at Socket A in mA (-1 if offline)')),
                ('socket_b_state', models.BooleanField(help_text='Is Socket B ON (True) or OFF (False)')),
                ('socket_b_mA', models.IntegerField(help_text='Current draw at Socket B in mA (-1 if offline)')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='outlets_tes_timesta_1c0174_idx'), models.Index(fields=['device_id', '-timestamp'], name='outlets_tes_device__ebe821_idx')],
            },
        ),
    ]
