# Generated by Django 5.2.9 on 2026-02-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0003_testeventlog_testtelemetrylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command_type', models.CharField(help_text='e.g., ADD_DEVICE, SET_MASTER_ID, CUT_POWER', max_length=50)),
                ('target_id', models.CharField(blank=True, help_text='e.g., 0xFE, NULL for broadcast', max_length=50, null=True)),
                ('payload', models.JSONField(help_text='Any extra command parameters')),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
