# Generated by Django 5.2.9 on 2026-02-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0003_eventlogtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlogtest',
            name='socket_label',
            field=models.CharField(blank=True, help_text='A, B, or AB', max_length=2),
        ),
    ]
