# Generated by Django 5.2.9 on 2026-02-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0003_firmware_aligned_schema'),
    ]

    operations = [
        # NOTE: RemoveField operations for energy, power, temperature, voltage
        # are skipped because those columns were never actually created in the DB
        # (migration 0003 was applied but the schema already matched).
        migrations.CreateModel(
            name='MainBreakerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccu_id', models.CharField(help_text="CCU sender ID, e.g. '01'", max_length=10)),
                ('current_ma', models.IntegerField(help_text='Total load current in mA from SCT sensor')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='outlets_mai_timesta_8e7c60_idx'), models.Index(fields=['ccu_id', '-timestamp'], name='outlets_mai_ccu_id_d9e89e_idx')],
            },
        ),
    ]
