# Generated by Django 5.2.9 on 2026-02-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_pendingcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testeventlog',
            name='action_type',
            field=models.CharField(choices=[('TOGGLE_RELAY', 'Toggle Relay'), ('SET_THRESHOLD', 'Set Threshold'), ('SET_MASTER_ID', 'Set Master ID'), ('ADD_DEVICE', 'Add Device'), ('DELETE_DEVICE', 'Delete Device'), ('OVERLOAD_TRIPPED', 'Overload Tripped'), ('ACK_RECEIVED', 'Command Acknowledged'), ('SYSTEM_BOOT', 'System Boot'), ('SYSTEM_CLEARED', 'System Cleared')], max_length=50),
        ),
    ]
