# Generated by Django 5.2.9 on 2026-02-23 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_remove_sensordata_energy_remove_sensordata_power_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralControlUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccu_id', models.CharField(help_text="CCU device ID, e.g. '01'", max_length=10, unique=True)),
                ('name', models.CharField(default='My CCU', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ccus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Central Control Unit',
                'verbose_name_plural': 'Central Control Units',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mainbreakerreading',
            name='ccu_device',
            field=models.ForeignKey(blank=True, help_text='Linked CCU device (auto-set from ccu_id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breaker_readings', to='outlets.centralcontrolunit'),
        ),
    ]
