# Generated by Django 5.2.9 on 2026-02-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_remove_sensordata_energy_remove_sensordata_power_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='power',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='voltage',
        ),
    ]
