# Generated by Django 5.2.9 on 2026-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0006_ccucommandqueue_alter_pendingcommand_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartOutletDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Hex ID e.g., 0xFE', max_length=10, unique=True)),
                ('name', models.CharField(default='Smart Outlet', max_length=100)),
                ('limit_mA', models.IntegerField(default=5000)),
                ('last_socket_a_state', models.BooleanField(default=False)),
                ('last_socket_a_mA', models.IntegerField(default=0)),
                ('last_socket_b_state', models.BooleanField(default=False)),
                ('last_socket_b_mA', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outlets_smartoutletdevice',
                'ordering': ['device_id'],
            },
        ),
        migrations.AlterModelTable(
            name='pendingcommand',
            table='outlets_pendingcommand',
        ),
    ]
