# Generated by Django 5.2.9 on 2026-03-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0006_remove_sensordata_energy_remove_sensordata_power_and_more'),
        ('outlets', '0007_smartoutletdevice_alter_pendingcommand_table'),
    ]

    operations = [
    ]
