# Generated by Django 5.2.9 on 2026-03-03 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0008_merge_20260303_2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='e.g. WEB_DASHBOARD, PIC_HARDWARE, SERVER', max_length=30)),
                ('action_type', models.CharField(help_text='e.g. TOGGLE_RELAY, OVERLOAD_TRIPPED, SET_THRESHOLD', max_length=30)),
                ('target_device', models.CharField(blank=True, help_text='e.g. 0xFE, All Devices', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CCUCommandQueue',
        ),
        migrations.DeleteModel(
            name='SmartOutletDevice',
        ),
        migrations.DeleteModel(
            name='TestEventLog',
        ),
        migrations.DeleteModel(
            name='TestTelemetryLog',
        ),
        migrations.AddField(
            model_name='centralcontrolunit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Last known LAN IP of this ESP32', null=True),
        ),
        migrations.AddField(
            model_name='centralcontrolunit',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time this CCU contacted the server', null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='ccu',
            field=models.ForeignKey(blank=True, help_text='Parent CCU (auto-set when ESP32 sends data)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlets', to='outlets.centralcontrolunit'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['-created_at'], name='outlets_eve_created_64ad0a_idx'),
        ),
    ]
