# Generated by Django 5.2.9 on 2026-03-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0009_eventlog_delete_ccucommandqueue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralcontrolunit',
            name='focused_device',
            field=models.CharField(blank=True, default='', help_text='Currently expanded outlet device_id (hex)', max_length=10),
        ),
    ]
