# Generated by Django 5.2.9 on 2026-03-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0010_centralcontrolunit_focused_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbreakerreading',
            name='threshold',
            field=models.IntegerField(default=0, help_text='Current threshold in mA for main breaker'),
        ),
    ]
