# Generated by Django 5.2.9 on 2026-03-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0011_add_threshold_to_mainbreakerreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralcontrolunit',
            name='breaker_threshold',
            field=models.IntegerField(default=15000, help_text='Main breaker overload threshold in mA'),
        ),
    ]
